<?php

// device fullname for mokee download web site
$devices_info = array(
    array('model' => 'a5dwg', 'name' => 'Desire 816', 'brand' => 'HTC'),
    array('model' => 'ace', 'name' => 'Desire HD (G10)', 'brand' => 'HTC'),
    array('model' => 'amami', 'name' => 'Xperia Z1 Compact', 'brand' => 'Sony'),
    array('model' => 'angler', 'name' => 'Nexus 6P', 'brand' => 'Google'),
    array('model' => 'aries', 'name' => 'Mi-2/Mi-2s', 'brand' => 'XiaoMi'),
    array('model' => 'armani', 'name' => 'RedMi 1s (C/W)', 'brand' => 'XiaoMi'),
    array('model' => 'athene', 'name' => 'Moto G4/G4 Plus', 'brand' => 'Motorola'),
    array('model' => 'bacon', 'name' => 'One', 'brand' => 'OnePlus'),
    array('model' => 'bullhead', 'name' => 'Nexus 5X', 'brand' => 'Google'),
    array('model' => 'cancro', 'name' => 'Mi-3w/Mi-4', 'brand' => 'XiaoMi'),
    array('model' => 'castor', 'name' => 'Xperia Z2 Tablet LTE', 'brand' => 'Sony'),
    array('model' => 'castor_windy', 'name' => 'Xperia Z2 Tablet WiFi', 'brand' => 'Sony'),
    array('model' => 'clark', 'name' => 'Moto X Style', 'brand' => 'Motorola'),
    array('model' => 'condor', 'name' => 'Moto E', 'brand' => 'Motorola'),
    array('model' => 'crespo', 'name' => 'Nexus S', 'brand' => 'Google'),
    array('model' => 'che10', 'name' => 'Honor 4X (China Telecom)', 'brand' => 'Huawei'),
    array('model' => 'cherry', 'name' => 'Honor 4/4X', 'brand' => 'Huawei'),
    array('model' => 'chm_cl00', 'name' => 'Honor 4C/P8 Lite (ChinaTelecom)', 'brand' => 'Huawei'),
    array('model' => 'cp8675', 'name' => 'Dazen F2', 'brand' => 'CoolPad'),
    array('model' => 'd2att', 'name' => 'Galaxy S III (AT&T)', 'brand' => 'Samsung'),
    array('model' => 'd2spr', 'name' => 'Galaxy S III (Sprint)', 'brand' => 'Samsung'),
    array('model' => 'd2tmo', 'name' => 'Galaxy S III (T-Mobile)', 'brand' => 'Samsung'),
    array('model' => 'd2vzw', 'name' => 'Galaxy S III (Verizon)', 'brand' => 'Samsung'),
    array('model' => 'd2lte', 'name' => 'Galaxy S III (Qualcomm Variants)', 'brand' => 'Samsung'),
    array('model' => 'd800', 'name' => 'G2 (AT&T)', 'brand' => 'LG'),
    array('model' => 'd801', 'name' => 'G2 (T-Mobile)', 'brand' => 'LG'),
    array('model' => 'd802', 'name' => 'G2 (Intl)', 'brand' => 'LG'),
    array('model' => 'd803', 'name' => 'G2 (Canada)', 'brand' => 'LG'),
    array('model' => 'd850', 'name' => 'G3 (AT&T)', 'brand' => 'LG'),
    array('model' => 'd851', 'name' => 'G3 (T-Mobile)', 'brand' => 'LG'),
    array('model' => 'd852', 'name' => 'G3 (Canada)', 'brand' => 'LG'),
    array('model' => 'd855', 'name' => 'G3 (Intl)', 'brand' => 'LG'),
    array('model' => 'd857', 'name' => 'G3 Dual SIM (D856/7/8/8hk/9)', 'brand' => 'LG'),
    array('model' => 'deb', 'name' => 'Nexus 7 2013 (LTE)', 'brand' => 'Google'),
    array('model' => 'dior', 'name' => 'Redmi Note 4g', 'brand' => 'XiaoMi'),
    array('model' => 'dlx', 'name' => 'Droid DNA', 'brand' => 'HTC'),
    array('model' => 'dogo', 'name' => 'Xperia ZR', 'brand' => 'Sony'),
    array('model' => 'e970', 'name' => 'Optimus G (AT&T)', 'brand' => 'LG'),
    array('model' => 'e975', 'name' => 'Optimus G (Intl)', 'brand' => 'LG'),
    array('model' => 'e980', 'name' => 'Optimus G Pro (All e98x GSM)', 'brand' => 'LG'),
    array('model' => 'edison', 'name' => 'Atrix 2', 'brand' => 'Motorola'),
    array('model' => 'endeavoru', 'name' => 'One X', 'brand' => 'HTC'),
    array('model' => 'enrc2b', 'name' => 'One X+', 'brand' => 'HTC'),
    array('model' => 'evita', 'name' => 'One XL', 'brand' => 'HTC'),
    array('model' => 'f320', 'name' => 'G2 (Korea)', 'brand' => 'LG'),
    array('model' => 'f400', 'name' => 'G3 (Korea)', 'brand' => 'LG'),
    array('model' => 'f460', 'name' => 'G3 Cat.6(Korea)', 'brand' => 'LG'),
    array('model' => 'falcon', 'name' => 'Moto G (Unified)', 'brand' => 'Motorola'),
    array('model' => 'ferrari', 'name' => 'Mi-4i', 'brand' => 'XiaoMi'),
    array('model' => 'find5', 'name' => 'Find 5', 'brand' => 'Oppo'),
    array('model' => 'find7', 'name' => 'Find 7 (A/S)', 'brand' => 'Oppo'),
    array('model' => 'find7s', 'name' => 'Find 7 (S)', 'brand' => 'Oppo'),
    array('model' => 'flo', 'name' => 'Nexus 7 2013 (Wi-Fi)', 'brand' => 'Google'),
    array('model' => 'flounder', 'name' => 'Nexus 9 (Wi-Fi)', 'brand' => 'Google'),
    array('model' => 'flounder_lte', 'name' => 'Nexus 9 (LTE)', 'brand' => 'Google'),
    array('model' => 'g620_a2', 'name' => 'G620-A2', 'brand' => 'Huawei'),
    array('model' => 'g750c', 'name' => 'B199', 'brand' => 'Huawei'),
    array('model' => 'g760l', 'name' => 'C199', 'brand' => 'Huawei'),
    array('model' => 'galaxysmtd', 'name' => 'Galaxy S', 'brand' => 'Samsung'),
    array('model' => 'gemini', 'name' => 'Mi-5', 'brand' => 'XiaoMi'),
    array('model' => 'ghost', 'name' => 'Moto X (Unified)', 'brand' => 'Motorola'),
    array('model' => 'griffin', 'name' => 'Moto Z 2016 (Unified)', 'brand' => 'Motorola'),
    array('model' => 'grouper', 'name' => 'Nexus 7 (Wi-Fi)', 'brand' => 'Google'),
    array('model' => 'h811', 'name' => 'G4 (T-Mobile)', 'brand' => 'LG'),
    array('model' => 'h815', 'name' => 'G4 (Intl)', 'brand' => 'LG'),
    array('model' => 'ham', 'name' => 'Z1', 'brand' => 'Zuk'),
    array('model' => 'hammerhead', 'name' => 'Nexus 5', 'brand' => 'Google'),
    array('model' => 'hammerheadcaf', 'name' => 'Nexus 5 CAF', 'brand' => 'Google'),
    array('model' => 'harpia', 'name' => 'Moto G4 Play', 'brand' => 'Motorola'),
    array('model' => 'hayabusa', 'name' => 'Xperia TX', 'brand' => 'Sony'),
    array('model' => 'herolte', 'name' => 'Galaxy S7 Flat', 'brand' => 'Samsung'),
    array('model' => 'hero2lte', 'name' => 'Galaxy S7 Edge', 'brand' => 'Samsung'),
    array('model' => 'hiaeuhl', 'name' => 'One A9 (GSM Intl)', 'brand' => 'HTC'),
    array('model' => 'hiaeul', 'name' => 'One A9 (GSM US)', 'brand' => 'HTC'),
    array('model' => 'hikari', 'name' => 'Xperia Arco S', 'brand' => 'Sony'),
    array('model' => 'himaul', 'name' => 'One M9 (GSM)', 'brand' => 'HTC'),
    array('model' => 'hlte', 'name' => 'Galaxy Note 3', 'brand' => 'Samsung'),
    array('model' => 'hltespr', 'name' => 'Galaxy Note 3 (Sprint)', 'brand' => 'Samsung'),
    array('model' => 'hltetmo', 'name' => 'Galaxy Note 3 (T-Mobile)', 'brand' => 'Samsung'),
    array('model' => 'hlteusc', 'name' => 'Galaxy Note 3 (US Cellular)', 'brand' => 'Samsung'),
    array('model' => 'hltevzw', 'name' => 'Galaxy Note 3 (Verizon)', 'brand' => 'Samsung'),
    array('model' => 'honami', 'name' => 'Xperia Z1', 'brand' => 'Sony'),
    array('model' => 'huashan', 'name' => 'Xperia SP', 'brand' => 'Sony'),
    array('model' => 'hummingbird', 'name' => 'Nook HD', 'brand' => 'Barnes & Noble'),
    array('model' => 'hydrogen', 'name' => 'Mi Max', 'brand' => 'XiaoMi'),
    array('model' => 'i605', 'name' => 'Galaxy Note II (Verizon)', 'brand' => 'Samsung'),
    array('model' => 'i925', 'name' => 'Galaxy Note 10.1 (Verizon)', 'brand' => 'Samsung'),
    array('model' => 'i9100', 'name' => 'Galaxy S II (Intl)', 'brand' => 'Samsung'),
    array('model' => 'i9100g', 'name' => 'Galaxy S II (G)', 'brand' => 'Samsung'),
    array('model' => 'i9300', 'name' => 'Galaxy S III (Intl)', 'brand' => 'Samsung'),
    array('model' => 'i9305', 'name' => 'Galaxy S III (GSM LTE)', 'brand' => 'Samsung'),
    array('model' => 'i9500', 'name' => 'Galaxy S4 (non-LTE)', 'brand' => 'Samsung'),
    array('model' => 'ido', 'name' => 'Redmi 3/Prime', 'brand' => 'XiaoMi'),
    array('model' => 'jalebi', 'name' => 'Yunique', 'brand' => 'YU'),
    array('model' => 'jflte', 'name' => 'Galaxy S4', 'brand' => 'Samsung'),
    array('model' => 'jflteatt', 'name' => 'Galaxy S4 (AT&T)', 'brand' => 'Samsung'),
    array('model' => 'jfltespr', 'name' => 'Galaxy S4 (Sprint)', 'brand' => 'Samsung'),
    array('model' => 'jfltetmo', 'name' => 'Galaxy S4 (T-Mobile)', 'brand' => 'Samsung'),
    array('model' => 'jfltevzw', 'name' => 'Galaxy S4 (Verizon)', 'brand' => 'Samsung'),
    array('model' => 'jfltexx', 'name' => 'Galaxy S4 (Intl)', 'brand' => 'Samsung'),
    array('model' => 'jsglte', 'name' => 'Galaxy S4 (China Mobile 4gLTE,GT-I9508V)', 'brand' => 'Samsung'),
    array('model' => 'jordanplus', 'name' => 'Defy / Defy Plus', 'brand' => 'Motorola'),
    array('model' => 'k3gduosctc', 'name' => 'Galaxy S5 (China Telecom 3G,SM-G9009D)', 'brand' => 'Samsung'),
    array('model' => 'k3gxx', 'name' => 'Galaxy S5 (Exynos Varient,SM-G900H)', 'brand' => 'Samsung'),
    array('model' => 'kccat6', 'name' => 'Galaxy S5 Plus', 'brand' => 'Samsung'),
    array('model' => 'kiwi', 'name' => 'Honor 5X', 'brand' => 'Huawei'),
    array('model' => 'klte', 'name' => 'Galaxy S5 (Intl,SM-G900F/M/T/S/L/K)', 'brand' => 'Samsung'),
    array('model' => 'kltechn', 'name' => 'Galaxy S5 (SM-G9006V,G9008V)', 'brand' => 'Samsung'),
    array('model' => 'kltechnduo', 'name' => 'Galaxy S5 (SM-G9006W,G9008W,G9009W)', 'brand' => 'Samsung'),
    array('model' => 'klteduos', 'name' => 'Galaxy S5 (SM-G900FD Dual SIM)', 'brand' => 'Samsung'),
    array('model' => 'kltedv', 'name' => 'Galaxy S5 (Vodafone,SM-G900I)', 'brand' => 'Samsung'),
    array('model' => 'kltekdi', 'name' => 'Galaxy S5 au (Japan SCL23,SC04F)', 'brand' => 'Samsung'),
    array('model' => 'kltekor', 'name' => 'Galaxy S5 (Korea)', 'brand' => 'Samsung'),
    array('model' => 'kltespr', 'name' => 'Galaxy S5 (Sprint G900P)', 'brand' => 'Samsung'),
    array('model' => 'klteusc', 'name' => 'Galaxy S5 (US Cellular,SM-G900R4/6/7)', 'brand' => 'Samsung'),
    array('model' => 'kltevzw', 'name' => 'Galaxy S5 (Verizon,SM-G900V)', 'brand' => 'Samsung'),
    array('model' => 'ks01lte', 'name' => 'Galaxy S4 LTE-A', 'brand' => 'Samsung'),
    array('model' => 'l01f', 'name' => 'G2 (Japan)', 'brand' => 'LG'),
    array('model' => 'l55t', 'name' => 'Xperia Z3 (TD-LTE)', 'brand' => 'Sony'),
    array('model' => 'l900', 'name' => 'Galaxy Note II (Sprint)', 'brand' => 'Samsung'),
    array('model' => 'le_x2', 'name' => 'Max2 (Le X820)', 'brand' => 'Letv'),
    array('model' => 'lentislte', 'name' => 'Galaxy S5 LTE-A', 'brand' => 'Samsung'),
    array('model' => 'leo', 'name' => 'Note Pro', 'brand' => 'XiaoMi'),
    array('model' => 'lettuce', 'name' => 'Yuphoria (YU5010)', 'brand' => 'YU'),
    array('model' => 'libra', 'name' => 'Mi-4c', 'brand' => 'XiaoMi'),
    array('model' => 'ls970', 'name' => 'Optimus G (Sprint)', 'brand' => 'LG'),
    array('model' => 'ls980', 'name' => 'G2 (Sprint)', 'brand' => 'LG'),
    array('model' => 'ls990', 'name' => 'G3 (Sprint)', 'brand' => 'LG'),
    array('model' => 'lt013g', 'name' => 'Galaxy Tab3 8" T311', 'brand' => 'Samsung'),
    array('model' => 'lt01lte', 'name' => 'Galaxy Tab3 8" T315', 'brand' => 'Samsung'),
    array('model' => 'lt01wifi', 'name' => 'Galaxy Tab3 8" T310', 'brand' => 'Samsung'),
    array('model' => 'lux', 'name' => 'Moto X Play', 'brand' => 'Motorola'),
    array('model' => 'm4', 'name' => 'One Mini', 'brand' => 'HTC'),
    array('model' => 'm7', 'name' => 'One (GSM)', 'brand' => 'HTC'),
    array('model' => 'm7spr', 'name' => 'One (Sprint)', 'brand' => 'HTC'),
    array('model' => 'm7vzw', 'name' => 'One (Verizon)', 'brand' => 'HTC'),
    array('model' => 'm8', 'name' => 'One 2014', 'brand' => 'HTC'),
    array('model' => 'm8d', 'name' => 'One 2014 Dual SIM', 'brand' => 'HTC'),
    array('model' => 'maguro', 'name' => 'Galaxy Nexus (GSM)', 'brand' => 'Google'),
    array('model' => 'mako', 'name' => 'Nexus 4', 'brand' => 'Google'),
    array('model' => 'marlin', 'name' => 'Pixel XL', 'brand' => 'Google'),
    array('model' => 'maserati', 'name' => 'Droid 4', 'brand' => 'Motorola'),
    array('model' => 'mb886', 'name' => 'Atrix HD', 'brand' => 'Motorola'),
    array('model' => 'mecdug', 'name' => 'One E8 (M8Sw/M8Sd)', 'brand' => 'HTC'),
    array('model' => 'merlin', 'name' => 'Moto G3 Turbo', 'brand' => 'Motorola'),
    array('model' => 'mint', 'name' => 'Xperia T', 'brand' => 'Sony'),
    array('model' => 'mione_plus', 'name' => 'Mi-1/Mi-1s', 'brand' => 'XiaoMi'),
    array('model' => 'moto_msm8960', 'name' => 'Atrix HD/Razr M/Razr HD', 'brand' => 'Motorola'),
    array('model' => 'moto_msm8960_jbbl', 'name' => 'Atrix HD/Razr M/Razr HD', 'brand' => 'Motorola'),
    array('model' => 'mt2', 'name' => 'Ascend Mate 2', 'brand' => 'Huawei'),
    array('model' => 'n1', 'name' => 'N1', 'brand' => 'Oppo'),
    array('model' => 'n3', 'name' => 'N3', 'brand' => 'Oppo'),
    array('model' => 'n7000', 'name' => 'Galaxy Note (Intl)', 'brand' => 'Samsung'),
    array('model' => 'n7100', 'name' => 'Galaxy Note II (GSM Non-LTE)', 'brand' => 'Samsung'),
    array('model' => 'nicki', 'name' => 'Xperia M', 'brand' => 'Sony'),
    array('model' => 'nozomi', 'name' => 'Xperia S', 'brand' => 'Sony'),
    array('model' => 'nx40x', 'name' => 'Z5 Mini', 'brand' => 'Nubia'),
    array('model' => 'nx403a', 'name' => 'Z5S Mini', 'brand' => 'Nubia'),
    array('model' => 'nx503a', 'name' => 'Z5S', 'brand' => 'Nubia'),
    array('model' => 'nx505j', 'name' => 'Z7 Max', 'brand' => 'Nubia'),
    array('model' => 'nx507j', 'name' => 'Z7 Mini', 'brand' => 'Nubia'),
    array('model' => 'nx510j', 'name' => 'Z9 Max', 'brand' => 'Nubia'),
    array('model' => 'nx511j', 'name' => 'Z9 Mini/Z9 Mini Elite(Marshmallow Only)', 'brand' => 'Nubia'),
    array('model' => 'nx523j', 'name' => 'Z11 Max (NX523J_V1)', 'brand' => 'Nubia'),
    array('model' => 'nx531j', 'name' => 'Z11', 'brand' => 'Nubia'),
    array('model' => 'obake', 'name' => 'Droid Mini/Ultra/MAXX', 'brand' => 'Motorola'),
    array('model' => 'odin', 'name' => 'Xperia ZL', 'brand' => 'Sony'),
    array('model' => 'onyx', 'name' => 'X', 'brand' => 'OnePlus'),
    array('model' => 'oneplus3', 'name' => 'Three', 'brand' => 'OnePlus'),
    array('model' => 'osprey', 'name' => 'Moto G (2015)', 'brand' => 'Motorola'),
    array('model' => 'otter', 'name' => 'Kindle Fire (1st gen)', 'brand' => 'Amazon'),
    array('model' => 'otter2', 'name' => 'Kindle Fire (2nd gen)', 'brand' => 'Amazon'),
    array('model' => 'otus', 'name' => 'Moto E (2015)', 'brand' => 'Motorola'),
    array('model' => 'ovation', 'name' => 'Nook HD+', 'brand' => 'Barnes & Noble'),
    array('model' => 'p1', 'name' => 'Galaxy Tab (GSM)', 'brand' => 'Samsung'),
    array('model' => 'p3100', 'name' => 'Galaxy Tab 2 7 (GSM)', 'brand' => 'Samsung'),
    array('model' => 'p3110', 'name' => 'Galaxy Tab 2 7 (Wi-Fi)', 'brand' => 'Samsung'),
    array('model' => 'p5100', 'name' => 'Galaxy Tab 2 10.1 (GSM)', 'brand' => 'Samsung'),
    array('model' => 'p5110', 'name' => 'Galaxy Tab 2 10.1 (Wi-Fi)', 'brand' => 'Samsung'),
    array('model' => 'p760', 'name' => 'Optimus L9', 'brand' => 'LG'),
    array('model' => 'p880', 'name' => 'Optimus 4X HD', 'brand' => 'LG'),
    array('model' => 'p930', 'name' => 'Nitro HD / Optimus LTE', 'brand' => 'LG'),
    array('model' => 'peach', 'name' => 'Benefit A3', 'brand' => 'ARK'),
    array('model' => 'peregrine', 'name' => 'Moto G LTE (Unified)', 'brand' => 'Motorola'),
    array('model' => 'pisces', 'name' => 'Mi-3td', 'brand' => 'XiaoMi'),
    array('model' => 'pyramid', 'name' => 'Sensation', 'brand' => 'HTC'),
    array('model' => 'quark', 'name' => 'Moto MAXX', 'brand' => 'Motorola'),
    array('model' => 'r5', 'name' => 'R5/R5s (Intl)', 'brand' => 'Oppo'),
    array('model' => 'r7plus', 'name' => 'R7 Plus', 'brand' => 'Oppo'),
    array('model' => 'r950', 'name' => 'Galaxy Note II (US Cellular)', 'brand' => 'Samsung'),
    array('model' => 'sailfish', 'name' => 'Pixel', 'brand' => 'Google'),
    array('model' => 'sambar', 'name' => 'Yutopia', 'brand' => 'YU'),
    array('model' => 'sc03e', 'name' => 'Galaxy S III LTE (Japan)', 'brand' => 'Samsung'),
    array('model' => 'seed', 'name' => 'Android One 2nd gen', 'brand' => 'Google'),
    array('model' => 'serrano3gxx', 'name' => 'Galaxy S4 Mini (3G)', 'brand' => 'Samsung'),
    array('model' => 'serranoltexx', 'name' => 'Galaxy S4 Mini (Intl)', 'brand' => 'Samsung'),
    array('model' => 'shamrock', 'name' => 'Android One 3rd gen', 'brand' => 'Google'),
    array('model' => 'shamu', 'name' => 'Nexus 6', 'brand' => 'Google'),
    array('model' => 'sirius', 'name' => 'Xperia Z2', 'brand' => 'Sony'),
    array('model' => 'skyrocket', 'name' => 'Galaxy S II Skyrocket', 'brand' => 'Samsung'),
    array('model' => 'sprout4', 'name' => 'Android One (4GB)', 'brand' => 'Google'),
    array('model' => 'sprout8', 'name' => 'Android One (8GB)', 'brand' => 'Google'),
    array('model' => 'spyder', 'name' => 'Droid Razr/Razr MAXX (CDMA)', 'brand' => 'Motorola'),
    array('model' => 'superior', 'name' => 'Galaxy Premier (WCDMA)', 'brand' => 'Samsung'),
    array('model' => 'superiorcmcc', 'name' => 'Galaxy Premier (TD-SCDMA)', 'brand' => 'Samsung'),
    array('model' => 'surnia', 'name' => 'Moto E LTE (2015)', 'brand' => 'Motorola'),
    array('model' => 't0lte', 'name' => 'Galaxy Note II (GSM LTE)', 'brand' => 'Samsung'),
    array('model' => 't6', 'name' => 'One Max (GSM)', 'brand' => 'HTC'),
    array('model' => 't6spr', 'name' => 'One Max (Sprint)', 'brand' => 'HTC'),
    array('model' => 't6vzw', 'name' => 'One Max (Verizon)', 'brand' => 'HTC'),
    array('model' => 'taoshan', 'name' => 'Xperia L', 'brand' => 'Sony'),
    array('model' => 'targa', 'name' => 'Droid Bionic', 'brand' => 'Motorola'),
    array('model' => 'thea', 'name' => 'Moto G 2014 LTE (Unified)', 'brand' => 'Motorola'),
    array('model' => 'tianchi', 'name' => 'Xperia T2 Ultra', 'brand' => 'Sony'),
    array('model' => 'tilapia', 'name' => 'Nexus 7 (GSM)', 'brand' => 'Google'),
    array('model' => 'titan', 'name' => 'Moto G 2014 (Unified)', 'brand' => 'Motorola'),
    array('model' => 'tocino', 'name' => 'Two', 'brand' => 'OnePlus'),
    array('model' => 'togari', 'name' => 'Xperia Z Ultra', 'brand' => 'Sony'),
    array('model' => 'togari_gpe', 'name' => 'Xperia Z Ultra (GPE)', 'brand' => 'Sony'),
    array('model' => 'tomato', 'name' => 'Yureka (AO5510)', 'brand' => 'YU'),
    array('model' => 'toro', 'name' => 'Galaxy Nexus (Verizon)', 'brand' => 'Google'),
    array('model' => 'tsubasa', 'name' => 'Xperia V', 'brand' => 'Sony'),
    array('model' => 'umts_spyder', 'name' => 'Razr/Razr MAXX (GSM)', 'brand' => 'Motorola'),
    array('model' => 'victara', 'name' => 'Moto X 2014 (Unified)', 'brand' => 'Motorola'),
    array('model' => 'victara_retcn', 'name' => 'Moto X 2014 (China)', 'brand' => 'Motorola'),
    array('model' => 'ville', 'name' => 'One S', 'brand' => 'HTC'),
    array('model' => 'vs980', 'name' => 'G2 (Verizon)', 'brand' => 'LG'),
    array('model' => 'vs985', 'name' => 'G3 (Verizon)', 'brand' => 'LG'),
    array('model' => 'wt88047', 'name' => 'RedMi 2', 'brand' => 'XiaoMi'),
    array('model' => 'kenzo', 'name' => 'Redmi Note 3', 'brand' => 'XiaoMi'),
    array('model' => 'x9180', 'name' => 'RedBull V5', 'brand' => 'ZTE'),
    array('model' => 'xt897', 'name' => 'Photon Q', 'brand' => 'Motorola'),
    array('model' => 'xt907', 'name' => 'Droid RAZR M', 'brand' => 'Motorola'),
    array('model' => 'xt925', 'name' => 'Droid RAZR HD (GSM)', 'brand' => 'Motorola'),
    array('model' => 'xt926', 'name' => 'Droid RAZR HD (CDMA)', 'brand' => 'Motorola'),
    array('model' => 'yuga', 'name' => 'Xperia Z', 'brand' => 'Sony'),
    array('model' => 'z00a', 'name' => 'Zenfone 2 (1080p)', 'brand' => 'Asus'),
    array('model' => 'z2', 'name' => 'Z2', 'brand' => 'Zuk'),
    array('model' => 'z2pro', 'name' => 'Z2PRO', 'brand' => 'Zuk'),
    array('model' => 'z3', 'name' => 'Xperia Z3', 'brand' => 'Sony'),
    array('model' => 'z3c', 'name' => 'Xperia Z3 Compact', 'brand' => 'Sony'),
    array('model' => 'z3dual', 'name' => 'Xperia Z3 Dual', 'brand' => 'Sony'),
    array('model' => 'zoom', 'name' => 'Lenovo Z90', 'brand' => 'Lenovo'),
);

$hardware_info = array(
    'angler' => array('cpu' => 'Qualcomm® Snapdragon™ 810',
                        'ram' => '3GB of LP-DDR4',
                        'ROM' => '16GB/32GB/128GB',
                        'battery' => '3450 mAh',
                        'display' => '5.7 inch, 1440x2560 pixel(518ppi)',
                        'cpuarch' => 'ARM64'),
    'aries' => array('cpu' => 'Qualcomm® Snapdragon™ APQ8064',
                     'ram' => '2GB of LP-DDR3',
                     'rom' => '16GB/64GB',
                     'battery' => '2000 mAh',
                     'display' => '4.3 inch, 1280x720 pixel(342ppi)',
                     'cpuarch' => 'ARM'),
    'armani' => array('cpu' => 'Qualcomm® Snapdragon™ MSM8628',
                     'ram' => '1GB of LP-DDR3',
                     'rom' => '8GB',
                     'battery' => '2000 mAh',
                     'display' => '4.7 inch, 1280x720 pixel(312ppi)',
                     'cpuarch' => 'ARM'),
    'athene' => array('cpu' => 'Qualcomm® Snapdragon™ 617',
                     'ram' => '2GB/3GB/4GB',
                     'rom' => '16GB/32GB/64GB',
                     'battery' => '3000 mAh',
                     'display' => '5.5 inch, 1920x1080 pixel(401ppi)',
                     'cpuarch' => 'ARM'),
    'bacon' => array('cpu' => 'Qualcomm® Snapdragon™ 801',
                     'ram' => '3GB of LP-DDR3',
                     'rom' => '16GB/64GB',
                     'battery' => '3100 mAh',
                     'display' => '5.5 inch, 1920x1080 pixel(401ppi)',
                     'cpuarch' => 'ARM'),
    'cancro' => array('cpu' => 'Qualcomm® Snapdragon™ 801',
                     'ram' => '3GB of LP-DDR3',
                     'rom' => '16GB/64GB',
                     'battery' => '3080 mAh',
                     'display' => '5 inch, 1920x1080 pixel(441ppi)',
                     'cpuarch' => 'ARM'),
    'che10' => array('cpu' => 'Qualcomm® Snapdragon™ 410',
                     'ram' => '2GB of LP-DDR3',
                     'rom' => '8GB',
                     'battery' => '3000 mAh',
                     'display' => '5.5 inch, 1280x720 pixel(267ppi)',
                     'cpuarch' => 'ARM'),
    'cherry' => array('cpu' => 'Qualcomm® Snapdragon™ 410',
                     'ram' => '2GB of LP-DDR3',
                     'rom' => '8GB',
                     'battery' => '3000 mAh',
                     'display' => '5.5 inch, 1280x720 pixel(267ppi)',
                     'cpuarch' => 'ARM'),
    'chm_cl00' => array('cpu' => 'Qualcomm® Snapdragon™ 615',
                     'ram' => '2GB of LP-DDR3',
                     'rom' => '8GB/16GB',
                     'battery' => '2550 mAh',
                     'display' => '5 inch, 1280x720 pixel(294ppi)',
                     'cpuarch' => 'ARM'),
    'clark' => array('cpu' => 'Qualcomm® Snapdragon™ 808',
                     'ram' => '3GB of LP-DDR3',
                     'rom' => '16GB/32GB/64GB',
                     'battery' => '3000 mAh',
                     'display' => '5.7 inch, 2560x1440 pixel(515ppi)',
                     'cpuarch' => 'ARM'),
    'cp8675' => array('cpu' => 'Qualcomm® Snapdragon™ 615',
                     'ram' => '2GB',
                     'rom' => '16GB',
                     'battery' => '2500 mAh',
                     'display' => '5.5 inch, 1280x720 pixel(267ppi)',
                     'cpuarch' => 'ARM'),
    'd857' => array('cpu' => 'Qualcomm® Snapdragon™ 801',
                     'ram' => '3GB',
                     'rom' => '32GB',
                     'battery' => '3000 mAh',
                     'display' => '5.5 inch, 2560x1440 pixel(538ppi)',
                     'cpuarch' => 'ARM'),
    'd802' =>array('cpu' => 'Qualcomm® Snapdragon™ 800',
                     'ram' => '2GB',
                     'rom' => '32GB',
                     'battery' => '3000 mAh',
                     'display' => '5.2 inch, 1920x1080 pixel(424ppi)',
                     'cpuarch' => 'ARM'),
    'd803' =>array('cpu' => 'Qualcomm® Snapdragon™ 800',
                     'ram' => '2GB',
                     'rom' => '32GB',
                     'battery' => '3000 mAh',
                     'display' => '5.2 inch, 1920x1080 pixel(424ppi)',
                     'cpuarch' => 'ARM'),
    'dior' => array('cpu' => 'Qualcomm® Snapdragon™ MSM8926',
                     'ram' => '2GB',
                     'rom' => '8GB',
                     'battery' => '3100 mAh',
                     'display' => '5.5 inch, 1280x720 pixel(267ppi)',
                     'cpuarch' => 'ARM'),
    'dogo' => array('cpu' => 'Qualcomm® Snapdragon™ S4 Pro APQ8064',
                     'ram' => '2GB',
                     'rom' => '8GB',
                     'battery' => '2300 mAh',
                     'display' => '4.55 inch, 1280x720 pixel(319ppi)',
                     'cpuarch' => 'ARM'),
    'falcon' => array('cpu' => 'Qualcomm® Snapdragon™ 400 MSM8226',
                      'ram' => '1GB',
                      'rom' => '16GB',
                      'display' => '4.5 inch, 1280 x 720 pixels(329ppi)',
                      'cpuarch' => 'ARM'),
    'f460' => array('cpu' => 'Qualcomm® Snapdragon™ APQ8084',
                     'ram' => '3GB',
                     'rom' => '32GB',
                     'battery' => '3000 mAh',
                     'display' => '5.5 inch, 2560x1440 pixel(538ppi)',
                     'cpuarch' => 'ARM'),
    'ferrari' => array('cpu' => 'Qualcomm® Snapdragon™ 615',
                     'ram' => '2GB of LP-DDR3',
                     'rom' => '16GB/64GB',
                     'battery' => '3080 mAh',
                     'display' => '5 inch, 1920x1080 pixel(441ppi)',
                     'cpuarch' => 'ARM64'),
    'find5' => array('cpu' => 'Qualcomm® Snapdragon™ APQ8064',
                     'ram' => '2GB',
                     'rom' => '16GB/32GB',
                     'battery' => '2500 mAh',
                     'display' => '5 inch, 1920x1080 pixel(424ppi)',
                     'cpuarch' => 'ARM'),
    'g750c' => array('cpu' => 'Qualcomm® Snapdragon™ MSM8628',
                     'ram' => '2GB of LP-DDR3',
                     'rom' => '16GB',
                     'battery' => '3000 mAh',
                     'display' => '5.5 inch, 1280x720 pixel(267ppi)',
                     'cpuarch' => 'ARM'),
    'g760l' => array('cpu' => 'Qualcomm® Snapdragon™ MSM8928',
                     'ram' => '2GB of LP-DDR3',
                     'rom' => '16GB',
                     'battery' => '3000 mAh',
                     'display' => '5.5 inch, 1280x720 pixel(267ppi)',
                     'cpuarch' => 'ARM'),
    'gemini' => array('cpu' => 'Qualcomm® Snapdragon™ 820',
                     'ram' => '3GB of LP-DDR4',
                     'rom' => '64GB',
                     'battery' => '3000 mAh',
                     'display' => '5.15 inch, 1920x1080 pixel(428ppi)',
                     'cpuarch' => 'ARM64'),
    'ham' => array('cpu' => 'Qualcomm® Snapdragon™ 801',
                     'ram' => '3GB',
                     'rom' => '64GB',
                     'battery' => '4100 mAh',
                     'display' => '5.5 inch, 1920x1080 pixel(401ppi)',
                     'cpuarch' => 'ARM'),
    'hammerhead' => array('cpu' => 'Qualcomm® Snapdragon™ MSM8974',
                     'ram' => '2GB',
                     'rom' => '16GB/32GB',
                     'battery' => '2300 mAh',
                     'display' => '4.95 inch, 1920x1080 pixel(445ppi)',
                     'cpuarch' => 'ARM'),
    'hammerheadcaf' => array('cpu' => 'Qualcomm® Snapdragon™ MSM8974',
                     'ram' => '2GB',
                     'rom' => '16GB/32GB',
                     'battery' => '2300 mAh',
                     'display' => '4.95 inch, 1920x1080 pixel(445ppi)',
                     'cpuarch' => 'ARM'),
    'herolte' => array('cpu' => 'Samsung Exynos 8890',
                     'ram' => '4GB',
                     'rom' => '32GB',
                     'battery' => '3000 mAh',
                     'display' => '5.1 inch, 2160x1440 pixels (577ppi)',
                     'cpuarch' => 'ARM64'),
    'hero2lte' => array('cpu' => 'Samsung Exynos 8890',
                     'ram' => '4GB',
                     'rom' => '32GB',
                     'battery' => '3600 mAh',
                     'display' => '5.5 inch, 2160x1440 pixels (534ppi)',
                     'cpuarch' => 'ARM64'),
    'honami' => array('cpu' => 'Qualcomm® Snapdragon™ MSM8274/MSM8974',
                     'ram' => '2GB',
                     'rom' => '16GB/32GB',
                     'battery' => '3000 mAh',
                     'display' => '5.0 inch, 1920x1080 pixel(441ppi)',
                     'cpuarch' => 'ARM'),
    'hydrogen' => array('cpu' => 'Qualcomm® Snapdragon™ 652/650',
                     'ram' => '3GB/4GB',
                     'rom' => '32GB/64GB/128GB',
                     'battery' => '4850 mAh',
                     'display' => '6.44 inch, 1920x1080 pixel(342ppi)',
                     'cpuarch' => 'Arm64'),
    'i9300' => array('cpu' => 'Samsung Exynos 4412',
                     'ram' => '1GB of LP-DDR3',
                     'rom' => '16GB',
                     'battery' => '2100 mAh',
                     'display' => '4.8 inch, 1280x720 pixel(306ppi)',
                     'cpuarch' => 'ARM'),
    'i9500' => array('cpu' => 'Samsung Exynos 5410',
                     'ram' => '2GB',
                     'rom' => '16GB',
                     'battery' => '2600 mAh',
                     'display' => '5.0 inch, 1920x1080 pixel(441ppi)',
                     'cpuarch' => 'ARM'),
    'ido' => array('cpu' => 'Qualcomm MSM8939v2 Snapdragon 616',
                     'ram' => '2GB/3GB',
                     'rom' => '16GB/32GB',
                     'battery' => '4000 mAh',
                     'display' => '5.0 inch, 720x1280 pixels(294ppi)',
                     'cpuarch' => 'ARM64'),
    'jalebi' => array('cpu' => 'Qualcomm® Snapdragon™ 410',
                     'ram' => '1GB/2GB',
                     'rom' => '8GB',
                     'battery' => '2200 mAh',
                     'display' => '4.7 inch, 1280x720 pixel(312ppi)',
                     'cpuarch' => 'ARM'),
    'jsglte' => array('cpu' => 'Qualcomm® Snapdragon™ 800',
                     'ram' => '2GB',
                     'rom' => '16GB',
                     'battery' => '2600 mAh',
                     'display' => '5.0 inch, 1920x1080 pixel(441ppi)',
                     'cpuarch' => 'ARM'),
    'jfltespr' => array('cpu' => 'Qualcomm® Snapdragon™ 800',
                     'ram' => '2GB',
                     'rom' => '16GB',
                     'battery' => '2600 mAh',
                     'display' => '5.0 inch, 1920x1080 pixel(441ppi)',
                     'cpuarch' => 'ARM'),
    'k3gduosctc' => array('cpu' => 'Qualcomm® Snapdragon™ 801',
                     'ram' => '2GB',
                     'rom' => '16GB',
                     'battery' => '2800 mAh',
                     'display' => '5.0 inch, 1920x1080 pixel(441ppi)',
                     'cpuarch' => 'ARM'),
    'k3gxx' => array('cpu' => 'Samsung Exynos 5422',
                     'ram' => '2GB',
                     'rom' => '16GB',
                     'battery' => '2800 mAh',
                     'display' => '5.1 inch, 1920x1080 pixel(432ppi)',
                     'cpuarch' => 'ARM'),
    'kccat6' => array('cpu' => 'Qualcomm® Snapdragon™ 805',
                     'ram' => '3GB',
                     'rom' => '32GB',
                     'battery' => '2800 mAh',
                     'display' => '5.0 inch, 1920x1080 pixel(441ppi)',
                     'cpuarch' => 'ARM'),
    'klte' => array('cpu' => 'Qualcomm® Snapdragon™ 801',
                     'ram' => '2GB',
                     'rom' => '16GB/32GB',
                     'battery' => '2800 mAh',
                     'display' => '5.0 inch, 1920x1080 pixel(441ppi)',
                     'cpuarch' => 'ARM'),
    'kltechn' => array('cpu' => 'Qualcomm® Snapdragon™ 801',
                     'ram' => '2GB',
                     'rom' => '16GB/32GB',
                     'battery' => '2800 mAh',
                     'display' => '5.0 inch, 1920x1080 pixel(441ppi)',
                     'cpuarch' => 'ARM'),
    'kltechnduo' => array('cpu' => 'Qualcomm® Snapdragon™ 801',
                     'ram' => '2GB',
                     'rom' => '16GB/32GB',
                     'battery' => '2800 mAh',
                     'display' => '5.0 inch, 1920x1080 pixel(441ppi)',
                     'cpuarch' => 'ARM'),
    'klteduos' => array('cpu' => 'Qualcomm® Snapdragon™ 801',
                     'ram' => '2GB',
                     'rom' => '16GB/32GB',
                     'battery' => '2800 mAh',
                     'display' => '5.0 inch, 1920x1080 pixel(441ppi)',
                     'cpuarch' => 'ARM'),
    'kltedv' => array('cpu' => 'Qualcomm® Snapdragon™ 801',
                     'ram' => '2GB',
                     'rom' => '16GB/32GB',
                     'battery' => '2800 mAh',
                     'display' => '5.0 inch, 1920x1080 pixel(441ppi)',
                     'cpuarch' => 'ARM'),
    'kltekdi' => array('cpu' => 'Qualcomm® Snapdragon™ 801',
                     'ram' => '2GB',
                     'rom' => '32GB',
                     'battery' => '2800 mAh',
                     'display' => '5.0 inch, 1920x1080 pixel(441ppi)',
                     'cpuarch' => 'ARM'),
    'kltespr' => array('cpu' => 'Qualcomm® Snapdragon™ 801',
                     'ram' => '2GB',
                     'rom' => '16GB/32GB',
                     'battery' => '2800 mAh',
                     'display' => '5.0 inch, 1920x1080 pixel(441ppi)',
                     'cpuarch' => 'ARM'),
    'l900' => array('cpu' => 'Samsung Exynos 4412',
                     'ram' => '2GB of LP-DDR3',
                     'rom' => '16GB',
                     'battery' => '3100 mAh',
                     'display' => '5.5 inch, 1280x720 pixel(267ppi)',
                     'cpuarch' => 'ARM'),
    'le_x2' => array('cpu' => 'Qualcomm® Snapdragon™ 820',
                     'ram' => '4-6GB of LP-DDR4',
                     'rom' => '64-128GB',
                     'battery' => '3100 mAh',
                     'display' => '5.7 inch, 1440x2560 pixel(515ppi)',
                     'cpuarch' => 'ARM64'),
    'lentislte' => array('cpu' => 'Qualcomm® Snapdragon™ 805',
                     'ram' => '3GB',
                     'rom' => '32GB',
                     'battery' => '2800 mAh',
                     'display' => '5.1 inch, 2560x1440 pixel(576ppi)',
                     'cpuarch' => 'ARM'),
    'leo' => array('cpu' => 'Qualcomm® Snapdragon™ 810',
                     'ram' => '4GB',
                     'rom' => '64GB',
                     'battery' => '3090 mAh',
                     'display' => '5.7 inch, 2560x1440 pixel(515ppi)',
                     'cpuarch' => 'ARM'),
    'libra' => array('cpu' => 'Qualcomm® Snapdragon™ 808',
                     'ram' => '2/3GB',
                     'rom' => '16/32GB',
                     'battery' => '3000 mAh',
                     'display' => '5.0 inch, 1920x1080 pixel(441ppi)',
                     'cpuarch' => 'ARM64'),
    'mako' => array('cpu' => 'Qualcomm® Snapdragon™ S4 Pro APQ8064',
                     'ram' => '2GB',
                     'rom' => '16GB/32GB',
                     'battery' => '2100 mAh',
                     'display' => '4.7 inch, 1280x768 pixel(317.6ppi)',
                     'cpuarch' => 'ARM'),
    'nicki' => array('cpu' => 'Qualcomm® Snapdragon™ S4 Plus MSM8227',
                     'ram' => '1GB',
                     'rom' => '4GB',
                     'battery' => '1750 mAh',
                     'display' => '4 inch, 480x854 pixel(245ppi)',
                     'cpuarch' => 'ARM'),
    'nx40x' => array('cpu' => 'Qualcomm® Snapdragon™ APQ8064',
                     'ram' => '2GB',
                     'rom' => '16GB',
                     'battery' => '2300 mAh',
                     'display' => '4.7 inch, 1280x720 pixel(312ppi)',
                     'cpuarch' => 'ARM'),
    'nx403a' => array('cpu' => 'Qualcomm® Snapdragon™ 600',
                     'ram' => '2GB',
                     'rom' => '16GB',
                     'battery' => '2000 mAh',
                     'display' => '4.7 inch, 1280x720 pixel(312ppi)',
                     'cpuarch' => 'ARM'),
    'nx503a' => array('cpu' => 'Qualcomm® Snapdragon™ 800',
                     'ram' => '2GB',
                     'rom' => '16/32GB',
                     'battery' => '2300 mAh',
                     'display' => '5.0 inch, 1920x1080 pixel(441ppi)',
                     'cpuarch' => 'ARM'),
    'nx505j' => array('cpu' => 'Qualcomm® Snapdragon™ 801',
                     'ram' => '2GB',
                     'rom' => '32GB',
                     'battery' => '3100 mAh',
                     'display' => '5.5 inch, 1920x1080 pixel(441ppi)',
                     'cpuarch' => 'ARM'),
    'nx507j' => array('cpu' => 'Qualcomm® Snapdragon™ 801',
                     'ram' => '2GB',
                     'rom' => '16GB',
                     'battery' => '2300 mAh',
                     'display' => '5 inch, 1920x1080 pixel(441ppi)',
                     'cpuarch' => 'ARM'),
    'nx510j' => array('cpu' => 'Qualcomm® Snapdragon™ 810',
                     'ram' => '3GB of LP-DDR4',
                     'rom' => '16GB',
                     'battery' => '2900 mAh',
                     'display' => '5.5 inch, 1920x1080 pixel(401ppi)',
                     'cpuarch' => 'ARM64'),
    'nx511j' => array('cpu' => 'Qualcomm® Snapdragon™ 615',
                     'ram' => '2GB/3G(Elite)',
                     'rom' => '16GB',
                     'battery' => '2900 mAh',
                     'display' => '5.0 inch, 1920x1080 pixel(441ppi)',
                     'cpuarch' => 'ARM64'),
    'nx523j' => array('cpu' => 'Qualcomm® Snapdragon™ 652',
                     'ram' => '4GB of LPDDR3',
                     'rom' => '64GB of eMMC 5.0',
                     'battery' => '4000 mAh',
                     'display' => '6.0 inch, 1920x1080 pixel(367ppi)',
                     'cpuarch' => 'ARM64'),
    'nx531j' => array('cpu' => 'Qualcomm® Snapdragon™ 820',
                     'ram' => '4GB/6G of LPDDR4',
                     'rom' => '64GB/128GB of eMMC 5.0',
                     'battery' => '3000 mAh',
                     'display' => '5.5 inch, 1920x1080 pixel(401ppi)',
                     'cpuarch' => 'ARM64'),
    'odin' => array('cpu' => 'Qualcomm® Snapdragon™ S4 Pro APQ8064',
                     'ram' => '2GB',
                     'rom' => '16GB',
                     'battery' => '2370 mAh',
                     'display' => '5.0 inch, 1920x1080 pixel(441ppi)',
                     'cpuarch' => 'ARM'),
    'onyx' => array('cpu' => 'Qualcomm® Snapdragon™ 801',
                     'ram' => '2GB/3GB of LP-DDR3',
                     'rom' => '16GB',
                     'battery' => '2525 mAh',
                     'display' => '5.0 inch, 1920x1080 pixel(441ppi)',
                     'cpuarch' => 'ARM'),
    'oneplus3' => array('cpu' => 'Qualcomm® Snapdragon™ 820',
                     'ram' => '6GB of LP-DDR4',
                     'rom' => '64GB',
                     'battery' => '3000 mAh',
                     'display' => '5.5 inch, 1920x1080 pixel(401ppi)',
                     'cpuarch' => 'ARM64'),
    'osprey' => array('cpu' => 'Qualcomm® Snapdragon™ 410',
                     'ram' => '1GB/2GB',
                     'rom' => '16GB',
                     'battery' => '2470 mAh',
                     'display' => '5.0 inch, 720x1280 pixel(294ppi)',
                     'cpuarch' => 'ARM'),
    'otus' => array('cpu' => 'Qualcomm® Snapdragon™ 200',
                     'ram' => '1GB',
                     'rom' => '8GB',
                     'battery' => '2390 mAh',
                     'display' => '4.5 inch, 540x960 pixel(245ppi)',
                     'cpuarch' => 'ARM'),
    'peach' => array('cpu' => 'Qualcomm Snapdragon™ 410',
                         'ram' => '1GB',
                         'rom' => '8GB',
                         'battery' => '2100 mAh',
                         'display' => '5.0 inch, 720x1280 pixel(294ppi)',
                         'cpuarch' => 'ARM'),
    'peregrine' => array('cpu' => 'Qualcomm Snapdragon™ 400',
                         'ram' => '1GB',
                         'rom' => '8GB',
                         'battery' => '2070 mAh',
                         'display' => '4.5 inch, 1280x720 pixel(329ppi)',
                         'cpuarch' => 'ARM'),
    'pisces' => array('cpu' => 'NVIDIA Tegra 4',
                     'ram' => '2GB',
                     'rom' => '16GB/64GB',
                     'battery' => '3050 mAh',
                     'display' => '5.0 inch, 1920x1080 pixel(441ppi)',
                     'cpuarch' => 'ARM'),
    'quark' => array('cpu' => 'Qualcomm® Snapdragon™ 805',
                     'ram' => '3GB',
                     'rom' => '64GB',
                     'battery' => '3900 mAh',
                     'display' => '5.2 inch, 1440x2560 pixel(565ppi)',
                     'cpuarch' => 'ARM'),
    'shamu' => array('cpu' => 'Qualcomm® Snapdragon™ 805',
                     'ram' => '3GB',
                     'rom' => '32G/64GB',
                     'battery' => '3220 mAh',
                     'display' => '5.96 inch, 2560x1440 pixel(493ppi)',
                     'cpuarch' => 'ARM'),
    'sprout4' => array('cpu' => 'MediaTek® MT6582',
                     'ram' => '1GB',
                     'rom' => '4GB',
                     'battery' => '1700 mAh',
                     'display' => '4.5 inch, 480x854 pixel(218ppi)',
                     'cpuarch' => 'ARM'),
    'sprout8' => array('cpu' => 'MediaTek® MT6582',
                     'ram' => '1GB',
                     'rom' => '8GB',
                     'battery' => '1700 mAh',
                     'display' => '4.5 inch, 480x854 pixel(218ppi)',
                     'cpuarch' => 'ARM'),
    'surnia' => array('cpu' => 'Qualcomm® Snapdragon™ 410',
                     'ram' => '1GB',
                     'rom' => '8GB',
                     'battery' => '2390 mAh',
                     'display' => '4.5 inch, 540x960 pixel(245ppi)',
                     'cpuarch' => 'ARM'),
    'thea' => array('cpu' => 'Qualcomm® Snapdragon™ MSM8926',
                     'ram' => '1GB',
                     'rom' => '8GB/16GB',
                     'battery' => '2390 mAh',
                     'display' => '5.0 inch, 1280x720 pixel(294ppi)',
                     'cpuarch' => 'ARM'),
    'titan' => array('cpu' => 'Qualcomm® Snapdragon™ 400 MSM8226',
                     'ram' => '1GB',
                     'rom' => '8GB/16GB',
                     'battery' => '2070 mAh',
                     'display' => '5.0 inch, 720x1280 pixel(294ppi)',
                     'cpuarch' => 'ARM'),
    'togari' => array('cpu' => 'Qualcomm® Snapdragon™ MSM8974',
                     'ram' => '2GB',
                     'rom' => '16GB',
                     'battery' => '3050 mAh',
                     'display' => '6.44 inch, 1920x1080 pixel(342ppi)',
                     'cpuarch' => 'ARM'),
    'togari_gpe' => array('cpu' => 'Qualcomm® Snapdragon™ MSM8974',
                     'ram' => '2GB',
                     'rom' => '16GB',
                     'battery' => '3050 mAh',
                     'display' => '6.44 inch, 1920x1080 pixel(342ppi)',
                     'cpuarch' => 'ARM'),
    'tomato' => array('cpu' => 'Qualcomm® Snapdragon™ 615',
                     'ram' => '2GB',
                     'rom' => '16GB',
                     'battery' => '2500 mAh',
                     'display' => '5.5 inch, 1280x720 pixel(267ppi)',
                     'cpuarch' => 'ARM64'),
    'toro' => array('cpu' => 'TI® OMAP™ 4460',
                     'ram' => '1GB',
                     'rom' => '16GB/32GB',
                     'battery' => '1850 mAh',
                     'display' => '4.7 inch, 1280x720 pixel(316ppi)',
                     'cpuarch' => 'ARM'),
    'tsubasa' => array('cpu' => 'Qualcomm® Snapdragon™ MSM8960',
                     'ram' => '1GB',
                     'rom' => '8GB',
                     'battery' => '1700 mAh',
                     'display' => '4.3 inch, 1280x720 pixel(342ppi)',
                     'cpuarch' => 'ARM'),
    'tocino' => array('cpu' => 'Qualcomm® Snapdragon™ 810',
                     'ram' => '3GB/4GB of LP-DDR4',
                     'rom' => '16GB/64GB',
                     'battery' => '3300 mAh',
                     'display' => '5.5 inch, 1920x1080 pixel(401ppi)',
                     'cpuarch' => 'ARM64'),
    'umts_spyder' => array('cpu' => 'TI® OMAP™ 4430',
                     'ram' => '1GB',
                     'rom' => '8GB',
                     'battery' => '1780 mAh/3300 mAh(MAXX)',
                     'display' => '4.3 inch, 960x540 pixel(256ppi)',
                     'cpuarch' => 'ARM'),
    'victara' => array('cpu' => 'Qualcomm® Snapdragon™ 801',
                     'ram' => '2GB',
                     'rom' => '16GB/32GB',
                     'battery' => '2300 mAh',
                     'display' => '5.2 inch, 1920x1080 pixel(424ppi)',
                     'cpuarch' => 'ARM'),
    'victara_retcn' => array('cpu' => 'Qualcomm® Snapdragon™ 801',
                     'ram' => '2GB',
                     'rom' => '16GB/32GB',
                     'battery' => '2300 mAh',
                     'display' => '5.2 inch, 1920x1080 pixel(424ppi)',
                     'cpuarch' => 'ARM'),
    'vs980' => array('cpu' => 'Qualcomm® Snapdragon™ 800',
                     'ram' => '2GB',
                     'rom' => '16GB/32GB',
                     'battery' => '3000 mAh',
                     'display' => '5.2 inch, 1920x1080 pixel(424ppi)',
                     'cpuarch' => 'ARM'),
    'vs985' => array('cpu' => 'Qualcomm® Snapdragon™ 801',
                     'ram' => '2GB/3GB',
                     'rom' => '16GB/32GB',
                     'battery' => '3000 mAh',
                     'display' => '5.5 inch, 2560x1440 pixel(538ppi)',
                     'cpuarch' => 'ARM'),
    'wt88047' => array('cpu' => 'Qualcomm® Snapdragon™ 410',
                     'ram' => '1GB/2GB',
                     'rom' => '8GB/16GB',
                     'battery' => '2200 mAh',
                     'display' => '4.7 inch, 1280x720 pixel(312ppi)',
                     'cpuarch' => 'ARM'),
    'kenzo' => array('cpu' => 'Qualcomm® Snapdragon™ 650',
                     'ram' => '2G/3GB',
                     'rom' => '16G/32GB',
                     'battery' => '4000 mAh',
                     'display' => '5.5 inch, 1920x1080 pixel(401ppi)',
                     'cpuarch' => 'ARM'),
    'x9180' => array('cpu' => 'Qualcomm® Snapdragon™ MSM8926',
                     'ram' => '2GB',
                     'rom' => '8GB',
                     'battery' => '2400 mAh',
                     'display' => '5 inch, 1280x720 pixel(294ppi)',
                     'cpuarch' => 'ARM'),
    'xt907' => array('cpu' => 'Qualcomm® Snapdragon™ MSM8960',
                     'ram' => '1GB',
                     'rom' => '8GB',
                     'battery' => '2000 mAh',
                     'display' => '4.3 inch, 960x540 pixel(256ppi)',
                     'cpuarch' => 'ARM'),
    'xt925' => array('cpu' => 'Qualcomm® Snapdragon™ MSM8960',
                     'ram' => '1GB',
                     'rom' => '16GB',
                     'battery' => '2530 mAh',
                     'display' => '4.7 inch, 1280x720 pixel(312ppi)',
                     'cpuarch' => 'ARM'),
    'xt926' => array('cpu' => 'Qualcomm® Snapdragon™ MSM8960',
                     'ram' => '1GB',
                     'rom' => '16GB',
                     'battery' => '2530 mAh',
                     'display' => '4.7 inch, 1280x720 pixel(312ppi)',
                     'cpuarch' => 'ARM'),
    'yuga' => array('cpu' => 'Qualcomm® Snapdragon™ S4 Pro APQ8064',
                     'ram' => '2GB',
                     'rom' => '16GB',
                     'battery' => '2370 mAh',
                     'display' => '5.0 inch, 1920x1080 pixel(441ppi)',
                     'cpuarch' => 'ARM'),
    'z2' => array('cpu' => 'Qualcomm® Snapdragon™ 820',
                     'ram' => '3GB/4GB',
                     'rom' => '32GB/64GB',
                     'battery' => '3100 mAh',
                     'display' => '5.0 inch, 1920x1080 pixel(441ppi)',
                     'cpuarch' => 'ARM'),
    'z2pro' => array('cpu' => 'Qualcomm® Snapdragon™ 820',
                     'ram' => '4GB',
                     'rom' => '64GB',
                     'battery' => '3100 mAh',
                     'display' => '5.2 inch, 1920x1080 pixel(424ppi)',
                     'cpuarch' => 'ARM'),
    'z3' => array('cpu' => 'Qualcomm® Snapdragon™ 801',
                     'ram' => '3GB',
                     'rom' => '16GB',
                     'battery' => '3100 mAh',
                     'display' => '5.2 inch, 1920x1080 pixel(424ppi)',
                     'cpuarch' => 'ARM'),
    'z3c' => array('cpu' => 'Qualcomm® Snapdragon™ 801',
                     'ram' => '2GB',
                     'rom' => '16GB',
                     'battery' => '2600 mAh',
                     'display' => '4.6 inch, 1280x720 pixel(319ppi)',
                     'cpuarch' => 'ARM'),
    'z3dual' => array('cpu' => 'Qualcomm® Snapdragon™ 801',
                     'ram' => '3GB',
                     'rom' => '16GB',
                     'battery' => '3100 mAh',
                     'display' => '5.2 inch, 1920x1080 pixel(424ppi)',
                     'cpuarch' => 'ARM'),
    'zoom' => array('cpu' => 'Qualcomm® Snapdragon™ 615',
                     'ram' => '3GB',
                     'rom' => '16GB/32GB',
                     'battery' => '2900 mAh',
                     'display' => '5.0 inch, 1920x1080 pixel(441ppi)',
                     'cpuarch' => 'ARM'),
);

foreach ($devices_info as $k => $val) {
    $device_info[$val['model']] = $val['brand'] . ' ' . $val['name'];
}
