<?php

// device fullname for mokee download web site
$devices_info = array(
    array('name' => 'Desire 816', 'brand' => 'HTC', 'model' => 'a5'),
    array('name' => 'Desire HD (G10)', 'brand' => 'HTC', 'model' => 'ace'),
    array('name' => 'Xperia Z1 Compact', 'brand' => 'Sony', 'model' => 'amami'),
    array('name' => 'Mi2/Mi2S', 'brand' => 'XiaoMi', 'model' => 'aries'),
    array('name' => 'RedMi 1S (C/W)', 'brand' => 'XiaoMi', 'model' => 'armani'),
    array('name' => 'One', 'brand' => 'OnePlus', 'model' => 'bacon'),
    array('name' => 'Mi3w/Mi4', 'brand' => 'XiaoMi', 'model' => 'cancro'),
    array('name' => 'Xperia Z2 Tablet LTE', 'brand' => 'Sony', 'model' => 'castor'),
    array('name' => 'Xperia Z2 Tablet WiFi', 'brand' => 'Sony', 'model' => 'castor_windy'),
    array('name' => 'Moto E', 'brand' => 'Motorola', 'model' => 'condor'),
    array('name' => 'Nexus S', 'brand' => 'Google', 'model' => 'crespo'),
    array('name' => 'Honor 4/4X (Kitkat)', 'brand' => 'Huawei', 'model' => 'c8817d'),
    array('name' => 'Honor 4/4X', 'brand' => 'Huawei', 'model' => 'cherry'),
    array('name' => 'Galaxy S III (AT&T)', 'brand' => 'Samsung', 'model' => 'd2att'),
    array('name' => 'Galaxy S III (Sprint)', 'brand' => 'Samsung', 'model' => 'd2spr'),
    array('name' => 'Galaxy S III (T-Mobile)', 'brand' => 'Samsung', 'model' => 'd2tmo'),
    array('name' => 'Galaxy S III (Verizon)', 'brand' => 'Samsung', 'model' => 'd2vzw'),
    array('name' => 'Galaxy S III (Qualcomm Variants)', 'brand' => 'Samsung', 'model' => 'd2lte'),
    array('name' => 'G2 (AT&T)', 'brand' => 'LG', 'model' => 'd800'),
    array('name' => 'G2 (T-Mobile)', 'brand' => 'LG', 'model' => 'd801'),
    array('name' => 'G2 (Intl)', 'brand' => 'LG', 'model' => 'd802'),
    array('name' => 'G2 (Canada)', 'brand' => 'LG', 'model' => 'd803'),
    array('name' => 'G3 (AT&T)', 'brand' => 'LG', 'model' => 'd850'),
    array('name' => 'G3 (T-Mobile)', 'brand' => 'LG', 'model' => 'd851'),
    array('name' => 'G3 (Canada)', 'brand' => 'LG', 'model' => 'd852'),
    array('name' => 'G3 (Intl)', 'brand' => 'LG', 'model' => 'd855'),
    array('name' => 'Nexus 7 2013 (LTE)', 'brand' => 'Google', 'model' => 'deb'),
    array('name' => 'Droid DNA', 'brand' => 'HTC', 'model' => 'dlx'),
    array('name' => 'Xperia ZR', 'brand' => 'Sony', 'model' => 'dogo'),
    array('name' => 'Optimus G (AT&T)', 'brand' => 'LG', 'model' => 'e970'),
    array('name' => 'Optimus G (Intl)', 'brand' => 'LG', 'model' => 'e975'),
    array('name' => 'Optimus G Pro (All e98x GSM)', 'brand' => 'LG', 'model' => 'e980'),
    array('name' => 'Atrix 2', 'brand' => 'Motorola', 'model' => 'edison'),
    array('name' => 'One X', 'brand' => 'HTC', 'model' => 'endeavoru'),
    array('name' => 'One X+', 'brand' => 'HTC', 'model' => 'enrc2b'),
    array('name' => 'One XL', 'brand' => 'HTC', 'model' => 'evita'),
    array('name' => 'Moto G (Unified)', 'brand' => 'Motorola', 'model' => 'falcon'),
    array('name' => 'Mi4i', 'brand' => 'XiaoMi', 'model' => 'ferrari'),
    array('name' => 'Find 5', 'brand' => 'Oppo', 'model' => 'find5'),
    array('name' => 'Find 7 (A/S)', 'brand' => 'Oppo', 'model' => 'find7'),
    array('name' => 'Find 7 (S)', 'brand' => 'Oppo', 'model' => 'find7s'),
    array('name' => 'Nexus 7 2013 (Wi-Fi)', 'brand' => 'Google', 'model' => 'flo'),
    array('name' => 'Nexus 9 (Wi-Fi)', 'brand' => 'Google', 'model' => 'flounder'),
    array('name' => 'G620-A2', 'brand' => 'Huawei', 'model' => 'g620_a2'),
    array('name' => 'Galaxy S', 'brand' => 'Samsung', 'model' => 'galaxysmtd'),
    array('name' => 'Moto X (Unified)', 'brand' => 'Motorola', 'model' => 'ghost'),
    array('name' => 'Nexus 7 (Wi-Fi)', 'brand' => 'Google', 'model' => 'grouper'),
    array('name' => 'Nexus 5', 'brand' => 'Google', 'model' => 'hammerhead'),
    array('name' => 'Nexus 5 CAF', 'brand' => 'Google', 'model' => 'hammerheadcaf'),
    array('name' => 'Xperia Arco S', 'brand' => 'Sony', 'model' => 'hikari'),
    array('name' => 'Galaxy Note 3', 'brand' => 'Samsung', 'model' => 'hlte'),
    array('name' => 'Galaxy Note 3 (Sprint)', 'brand' => 'Samsung', 'model' => 'hltespr'),
    array('name' => 'Galaxy Note 3 (T-Mobile)', 'brand' => 'Samsung', 'model' => 'hltetmo'),
    array('name' => 'Galaxy Note 3 (US Cellular)', 'brand' => 'Samsung', 'model' => 'hlteusc'),
    array('name' => 'Galaxy Note 3 (Verizon)', 'brand' => 'Samsung', 'model' => 'hltevzw'),
    array('name' => 'Xperia Z1', 'brand' => 'Sony', 'model' => 'honami'),
    array('name' => 'Xperia SP', 'brand' => 'Sony', 'model' => 'huashan'),
    array('name' => 'Nook HD', 'brand' => 'Barnes & Noble', 'model' => 'hummingbird'),
    array('name' => 'Galaxy Note II (Verizon)', 'brand' => 'Samsung', 'model' => 'i605'),
    array('name' => 'Galaxy Note 10.1 (Verizon)', 'brand' => 'Samsung', 'model' => 'i925'),
    array('name' => 'Galaxy S II (Intl)', 'brand' => 'Samsung', 'model' => 'i9100'),
    array('name' => 'Galaxy S II (G)', 'brand' => 'Samsung', 'model' => 'i9100g'),
    array('name' => 'Galaxy S III (Intl)', 'brand' => 'Samsung', 'model' => 'i9300'),
    array('name' => 'Galaxy S III (GSM LTE)', 'brand' => 'Samsung', 'model' => 'i9305'),
    array('name' => 'Galaxy S4 (non-LTE)', 'brand' => 'Samsung', 'model' => 'i9500'),
    array('name' => 'Galaxy S4', 'brand' => 'Samsung', 'model' => 'jflte'),
    array('name' => 'Galaxy S4 (AT&T)', 'brand' => 'Samsung', 'model' => 'jflteatt'),
    array('name' => 'Galaxy S4 (Sprint)', 'brand' => 'Samsung', 'model' => 'jfltespr'),
    array('name' => 'Galaxy S4 (T-Mobile)', 'brand' => 'Samsung', 'model' => 'jfltetmo'),
    array('name' => 'Galaxy S4 (Verizon)', 'brand' => 'Samsung', 'model' => 'jfltevzw'),
    array('name' => 'Galaxy S4 (Intl)', 'brand' => 'Samsung', 'model' => 'jfltexx'),
    array('name' => 'Defy / Defy Plus', 'brand' => 'Motorola', 'model' => 'jordanplus'),
    array('name' => 'Galaxy S5 (GSM)', 'brand' => 'Samsung', 'model' => 'klte'),
    array('name' => 'Galaxy S5 (China)', 'brand' => 'Samsung', 'model' => 'kltechn'),
    array('name' => 'Galaxy S5 (China Dual SIM)', 'brand' => 'Samsung', 'model' => 'kltechnduo'),
    array('name' => 'Galaxy S5 (SM-G900FD Dual SIM)', 'brand' => 'Samsung', 'model' => 'klteduos'),
    array('name' => 'Galaxy S5 au (KDDI)', 'brand' => 'Samsung', 'model' => 'kltekdi'),
    array('name' => 'Galaxy S5 (Sprint)', 'brand' => 'Samsung', 'model' => 'kltespr'),
    array('name' => 'Galaxy S5 (US Cellular)', 'brand' => 'Samsung', 'model' => 'klteusc'),
    array('name' => 'Galaxy S5 (Verizon)', 'brand' => 'Samsung', 'model' => 'kltevzw'),
    array('name' => 'Galaxy S4 LTE-A', 'brand' => 'Samsung', 'model' => 'ks01lte'),
    array('name' => 'G2 (Japan)', 'brand' => 'LG', 'model' => 'l01f'),
    array('name' => 'Xperia Z3 (TD-LTE)', 'brand' => 'Sony', 'model' => 'l55t'),
    array('name' => 'Galaxy Note II (Sprint)', 'brand' => 'Samsung', 'model' => 'l900'),
    array('name' => 'Yuphoria (YU5010)', 'brand' => 'YU', 'model' => 'lettuce'),
    array('name' => 'Optimus G (Sprint)', 'brand' => 'LG', 'model' => 'ls970'),
    array('name' => 'G2 (Sprint)', 'brand' => 'LG', 'model' => 'ls980'),
    array('name' => 'G3 (Sprint)', 'brand' => 'LG', 'model' => 'ls990'),
    array('name' => 'Galaxy Tab3 8" T311', 'brand' => 'Samsung', 'model' => 'lt013g'),
    array('name' => 'Galaxy Tab3 8" T315', 'brand' => 'Samsung', 'model' => 'lt01lte'),
    array('name' => 'Galaxy Tab3 8" T310', 'brand' => 'Samsung', 'model' => 'lt01wifi'),
    array('name' => 'One Mini', 'brand' => 'HTC', 'model' => 'm4'),
    array('name' => 'One (GSM)', 'brand' => 'HTC', 'model' => 'm7'),
    array('name' => 'One (Sprint)', 'brand' => 'HTC', 'model' => 'm7spr'),
    array('name' => 'One (Verizon)', 'brand' => 'HTC', 'model' => 'm7vzw'),
    array('name' => 'One 2014', 'brand' => 'HTC', 'model' => 'm8'),
    array('name' => 'One 2014 Dual SIM', 'brand' => 'HTC', 'model' => 'm8d'),
    array('name' => 'Galaxy Nexus (GSM)', 'brand' => 'Google', 'model' => 'maguro'),
    array('name' => 'Nexus 4', 'brand' => 'Google', 'model' => 'mako'),
    array('name' => 'Droid 4', 'brand' => 'Motorola', 'model' => 'maserati'),
    array('name' => 'Atrix HD', 'brand' => 'Motorola', 'model' => 'mb886'),
    array('name' => 'Xperia T', 'brand' => 'Sony', 'model' => 'mint'),
    array('name' => 'Mi1 / Mi1S', 'brand' => 'XiaoMi', 'model' => 'mione_plus'),
    array('name' => 'Atrix HD / Razr M / Razr HD / Electrify M', 'brand' => 'Motorola', 'model' => 'moto_msm8960'),
    array('name' => 'Atrix HD / Razr M / Razr HD / Electrify M (JBBL)', 'brand' => 'Motorola', 'model' => 'moto_msm8960_jbbl'),
    array('name' => 'N1', 'brand' => 'Oppo', 'model' => 'n1'),
    array('name' => 'N3', 'brand' => 'Oppo', 'model' => 'n3'),
    array('name' => 'Galaxy Note (Intl)', 'brand' => 'Samsung', 'model' => 'n7000'),
    array('name' => 'Galaxy Note II (GSM Non-LTE)', 'brand' => 'Samsung', 'model' => 'n7100'),
    array('name' => 'Xperia M', 'brand' => 'Sony', 'model' => 'nicki'),
    array('name' => 'Xperia S', 'brand' => 'Sony', 'model' => 'nozomi'),
    array('name' => 'Z5 Mini', 'brand' => 'Nubia', 'model' => 'nx40x'),
    array('name' => 'Z5S Mini', 'brand' => 'Nubia', 'model' => 'nx403a'),
    array('name' => 'Z5S', 'brand' => 'Nubia', 'model' => 'nx503a'),
    array('name' => 'Z7 Mini', 'brand' => 'Nubia', 'model' => 'nx507j'),
    array('name' => 'Z9 Max', 'brand' => 'Nubia', 'model' => 'nx510j'),
    array('name' => 'Droid Mini / Ultra / MAXX', 'brand' => 'Motorola', 'model' => 'obake'),
    array('name' => 'Xperia ZL', 'brand' => 'Sony', 'model' => 'odin'),
    array('name' => 'Moto G (2015)', 'brand' => 'Motorola', 'model' => 'osprey'),
    array('name' => 'Kindle Fire (1st gen)', 'brand' => 'Amazon', 'model' => 'otter'),
    array('name' => 'Kindle Fire (2nd gen)', 'brand' => 'Amazon', 'model' => 'otter2'),
    array('name' => 'Moto E (2015)', 'brand' => 'Motorola', 'model' => 'otus'),
    array('name' => 'Nook HD+', 'brand' => 'Barnes & Noble', 'model' => 'ovation'),
    array('name' => 'Galaxy Tab (GSM)', 'brand' => 'Samsung', 'model' => 'p1'),
    array('name' => 'Galaxy Tab 2 7 (GSM)', 'brand' => 'Samsung', 'model' => 'p3100'),
    array('name' => 'Galaxy Tab 2 7 (Wi-Fi)', 'brand' => 'Samsung', 'model' => 'p3110'),
    array('name' => 'Galaxy Tab 2 10.1 (GSM)', 'brand' => 'Samsung', 'model' => 'p5100'),
    array('name' => 'Galaxy Tab 2 10.1 (Wi-Fi)', 'brand' => 'Samsung', 'model' => 'p5110'),
    array('name' => 'Optimus L9', 'brand' => 'LG', 'model' => 'p760'),
    array('name' => 'Optimus 4X HD', 'brand' => 'LG', 'model' => 'p880'),
    array('name' => 'Nitro HD / Optimus LTE', 'brand' => 'LG', 'model' => 'p930'),
    array('name' => 'Moto G LTE (Unified)', 'brand' => 'Motorola', 'model' => 'peregrine'),
    array('name' => 'Mi3TD', 'brand' => 'XiaoMi', 'model' => 'pisces'),
    array('name' => 'Sensation', 'brand' => 'HTC', 'model' => 'pyramid'),
    array('name' => 'Moto MAXX', 'brand' => 'Motorola', 'model' => 'quark'),
    array('name' => 'R7 Plus', 'brand' => 'Oppo', 'model' => 'r7plus'),
    array('name' => 'Galaxy Note II (US Cellular)', 'brand' => 'Samsung', 'model' => 'r950'),
    array('name' => 'Galaxy S III LTE (Japan)', 'brand' => 'Samsung', 'model' => 'sc03e'),
    array('name' => 'Galaxy S4 Mini (3G)', 'brand' => 'Samsung', 'model' => 'serrano3gxx'),
    array('name' => 'Galaxy S4 Mini (Intl)', 'brand' => 'Samsung', 'model' => 'serranoltexx'),
    array('name' => 'Nexus 6', 'brand' => 'Google', 'model' => 'shamu'),
    array('name' => 'Xperia Z2', 'brand' => 'Sony', 'model' => 'sirius'),
    array('name' => 'Galaxy S II Skyrocket', 'brand' => 'Samsung', 'model' => 'skyrocket'),
    array('name' => 'Droid Razr / Razr MAXX (CDMA)', 'brand' => 'Motorola', 'model' => 'spyder'),
    array('name' => 'Galaxy Premier (WCDMA)', 'brand' => 'Samsung', 'model' => 'superior'),
    array('name' => 'Galaxy Premier (TD-SCDMA)', 'brand' => 'Samsung', 'model' => 'superiorcmcc'),
    array('name' => 'Moto E LTE (2015)', 'brand' => 'Motorola', 'model' => 'surnia'),
    array('name' => 'Galaxy Note II (GSM LTE)', 'brand' => 'Samsung', 'model' => 't0lte'),
    array('name' => 'One Max (GSM)', 'brand' => 'HTC', 'model' => 't6'),
    array('name' => 'One Max (Sprint)', 'brand' => 'HTC', 'model' => 't6spr'),
    array('name' => 'One Max (Verizon)', 'brand' => 'HTC', 'model' => 't6vzw'),
    array('name' => 'Xperia L', 'brand' => 'Sony', 'model' => 'taoshan'),
    array('name' => 'Droid Bionic', 'brand' => 'Motorola', 'model' => 'targa'),
    array('name' => 'Moto G 2014 LTE (Unified)', 'brand' => 'Motorola', 'model' => 'thea'),
    array('name' => 'Xperia T2 Ultra', 'brand' => 'Sony', 'model' => 'tianchi'),
    array('name' => 'Nexus 7 (GSM)', 'brand' => 'Google', 'model' => 'tilapia'),
    array('name' => 'Moto G 2014 (Unified)', 'brand' => 'Motorola', 'model' => 'titan'),
    array('name' => 'Two', 'brand' => 'OnePlus', 'model' => 'tocino'),
    array('name' => 'Xperia Z Ultra', 'brand' => 'Sony', 'model' => 'togari'),
    array('name' => 'Xperia Z Ultra (GPE)', 'brand' => 'Sony', 'model' => 'togari_gpe'),
    array('name' => 'Yureka (AO5510)', 'brand' => 'YU', 'model' => 'tomato'),
    array('name' => 'Galaxy Nexus (Verizon)', 'brand' => 'Google', 'model' => 'toro'),
    array('name' => 'Galaxy Nexus (Sprint)', 'brand' => 'Google', 'model' => 'toroplus'),
    array('name' => 'Xperia V', 'brand' => 'Sony', 'model' => 'tsubasa'),
    array('name' => 'Razr / Razr MAXX (GSM)', 'brand' => 'Motorola', 'model' => 'umts_spyder'),
    array('name' => 'Moto X 2014 (Unified)', 'brand' => 'Motorola', 'model' => 'victara'),
    array('name' => 'Moto X 2014 (China)', 'brand' => 'Motorola', 'model' => 'victara_retcn'),
    array('name' => 'One S', 'brand' => 'HTC', 'model' => 'ville'),
    array('name' => 'G2 (Verizon)', 'brand' => 'LG', 'model' => 'vs980'),
    array('name' => 'G3 (Verizon)', 'brand' => 'LG', 'model' => 'vs985'),
    array('name' => 'RedBull V5', 'brand' => 'ZTE', 'model' => 'x9180'),
    array('name' => 'Photon Q', 'brand' => 'Motorola', 'model' => 'xt897'),
    array('name' => 'Droid RAZR M', 'brand' => 'Motorola', 'model' => 'xt907'),
    array('name' => 'Droid RAZR HD (GSM)', 'brand' => 'Motorola', 'model' => 'xt925'),
    array('name' => 'Droid RAZR HD JBBL', 'brand' => 'Motorola', 'model' => 'xt925_jbbl'),
    array('name' => 'Droid RAZR HD (CDMA)', 'brand' => 'Motorola', 'model' => 'xt926'),
    array('name' => 'Xperia Z', 'brand' => 'Sony', 'model' => 'yuga'),
    array('name' => 'Xperia Z3', 'brand' => 'Sony', 'model' => 'z3'),
    array('name' => 'Xperia Z3 Compact', 'brand' => 'Sony', 'model' => 'z3c'),
);

$hardware_info = array(
    'bacon' => array('cpu' => 'Qualcomm® Snapdragon™ 801',
                     'ram' => '3GB of LP-DDR3',
                     'rom' => '16GB/64GB',
                     'battery' => '3100 mAh'),
    'shamu' => array('cpu' => 'Qualcomm® Snapdragon™ 805',
                     'ram' => '3GB',
                     'rom' => '32G/64GB',
                     'battery' => '3220 mAh'),
    'tocino' => array('cpu' => 'Qualcomm® Snapdragon™ 810',
                      'ram' => '3GB/4GB of LP-DDR4',
                      'rom' => '16GB/64GB',
                      'battery' => '3300 mAh'),
    'yuga' => array('cpu' => 'Qualcomm® Snapdragon™ 800',
                    'ram' => '2GB',
                    'rom' => '16GB',
                    'battery' => '3000 mAh'),
);

foreach ($devices_info as $k => $val) {
    $device_info[$val['model']] = $val['brand'] . ' ' . $val['name'];
}
