<?php
$maintainers_info = array(
    'che10' => array('name' => 'dianlujitao',
                     'url' => 'http://weibo.com/dianlujitao'),
    'cherry' => array('name' => 'dianlujitao',
                     'url' => 'http://weibo.com/dianlujitao'),
    'cp8675' => array('name' => 'Flour_Mo',
                     'url' => 'http://weibo.com/2036597861'),
    'd857' => array('name' => '豆浆炒蛋',
                     'url' => 'http://weibo.com/3921475456'),
    'dior' => array('name' => '子龙zj',
                    'url' => 'http://weibo.com/zj502407679'),
    'f460' => array('name' => 'shminer',
                     'url' => 'http://weibo.com/JZshminer'),
    'gemini' => array('name' => 'xiaobai不会写shell',
                     'url' => 'http://weibo.com/3138080394'),
    'kenzo' => array('name' => 'Flour_Mo',
                     'url' => 'http://weibo.com/2036597861'),
    'libra' => array('name' => 'xiaobai不会写shell',
                     'url' => 'http://weibo.com/3138080394'),
    'nx531j' => array('name' => 'XiNGRZ',
                     'url' => 'http://weibo.com/1260797924'),
    'oneplus3' => array('name' => 'dianlujitao',
                     'url' => 'http://weibo.com/dianlujitao'),
    'onyx' => array('name' => '皓睿睡不着与皓睿起不来',
                     'url' => 'http://weibo.com/1311032140'),
    'z2pro' => array('name' => 'Flour_Mo',
                     'url' => 'http://weibo.com/2036597861'),
);
