<?php
$maintainers_info = array(
    'aries' => array('name' => '乖奕虎',
                     'url' => 'http://weibo.com/guaiyihu'),
    'cancro' => array('name' => '乖奕虎',
                     'url' => 'http://weibo.com/guaiyihu'),
    'che10' => array('name' => 'dianlujitao',
                     'url' => 'http://weibo.com/dianlujitao'),
    'cheeseburger' => array('name' => 'XiNGRZ',
                     'url' => 'http://weibo.com/xingrz'),
    'cherry' => array('name' => 'dianlujitao',
                     'url' => 'http://weibo.com/dianlujitao'),
    'cp8675' => array('name' => 'Flour_Mo',
                     'url' => 'http://weibo.com/2036597861'),
    'd857' => array('name' => '豆浆炒蛋',
                     'url' => 'http://weibo.com/3921475456'),
    'dior' => array('name' => '子龙zj',
                    'url' => 'http://weibo.com/zj502407679'),
    'dumpling' => array('name' => 'XiNGRZ',
                     'url' => 'http://weibo.com/xingrz'),
    'f460' => array('name' => 'shminer',
                     'url' => 'http://weibo.com/JZshminer'),
    'g760l' => array('name' => 'xjljian',
                     'url' => 'http://weibo.com/2144909502'),
    'herolte' => array('name' => '8890dev Organization',
                     'url' => 'https://github.com/8890dev'),
    'hero2lte' => array('name' => '8890dev Organization',
                     'url' => 'https://github.com/8890dev'),
    'hydrogen' => array('name' => 'zhaochengw',
                     'url' => 'http://weibo.com/1649884475'),
    'ido' => array('name' => 'EsromG5',
                     'url' => 'http://github.com/EsromG5'),
    'j5ltexx' => array('name' => 'EsromG5',
                     'url' => 'http://github.com/EsromG5'),
    'j5nltexx' => array('name' => 'EsromG5',
                     'url' => 'http://github.com/EsromG5'),
    'jason' => array('name' => 'dianlujitao',
                     'url' => 'http://weibo.com/dianlujitao'),
    'jsglte' => array('name' => 'luo2888',
                     'url' => 'http://weibo.com/kwangaho'),
    'k3gduosctc' => array('name' => 'luo2888',
                     'url' => 'http://weibo.com/kwangaho'),
    'kenzo' => array('name' => 'Carlos Arriaga',
                     'url' => 'https://plus.google.com/u/0/+CarlosArriagaCM'),
    'kltekdi' => array('name' => 'luo2888',
                     'url' => 'http://weibo.com/kwangaho'),
    'land' => array('name' => 'IsaacChen',
                     'url' => 'http://weibo.com/tingyiisaac'),
    'le_x2' => array('name' => 'zhaochengw',
                     'url' => 'http://weibo.com/1649884475'),
    'leo' => array('name' => '乖奕虎',
                     'url' => 'http://weibo.com/guaiyihu'),
    'libra' => array('name' => 'xiaobai不会写shell',
                     'url' => 'http://weibo.com/3138080394'),
    'nx510j' => array('name' => 'zhaochengw',
                     'url' => 'http://weibo.com/1649884475'),
    'nx523j' => array('name' => 'zhaochengw',
                     'url' => 'http://weibo.com/1649884475'),
    'nx529j' => array('name' => 'S___Y__',
                     'url' => 'http://weibo.com/2434134362'),
    'nx531j' => array('name' => 'XiNGRZ',
                     'url' => 'http://weibo.com/xingrz'),
    'nx549j' => array('name' => 'S___Y__',
                     'url' => 'http://weibo.com/2434134362'),
    'nx563j' => array('name' => 'S___Y__',
                     'url' => 'http://weibo.com/2434134362'),
    'nx569j' => array('name' => 'S___Y__',
                     'url' => 'http://weibo.com/2434134362'),
    'nx595j' => array('name' => 'S___Y__',
                     'url' => 'http://weibo.com/2434134362'),
    'oneplus3' => array('name' => 'dianlujitao',
                     'url' => 'http://weibo.com/dianlujitao'),
    'onyx' => array('name' => '皓睿睡不着与皓睿起不来',
                     'url' => 'http://weibo.com/1311032140'),
    'peach' => array('name' => 'lolmaxlik',
                     'url' => 'https://plus.google.com/u/0/117066718532703598783'),
    'rk3288' => array('name' => 'XiNGRZ',
                     'url' => 'http://weibo.com/xingrz'),
    'rolex' => array('name' => 'ManuCarmona',
                     'url' => 'https://github.com/manuelcarmona'),
    'sagit' => array('name' => 'xiaobai不会写shell',
                     'url' => 'http://weibo.com/3138080394'),
    'santoni' => array('name' => 'IsaacChen',
                     'url' => 'http://weibo.com/tingyiisaac'),
    'satsuki' => array('name' => 'parhelia',
                     'url' => 'http://weibo.com/parheliamm'),
    'scorpio' => array('name' => 'nian0114',
                     'url' => 'http://weibo.com/nian0114'),
    'sumire' => array('name' => 'parhelia',
                     'url' => 'http://weibo.com/parheliamm'),
    'suzuran' => array('name' => 'parhelia',
                     'url' => 'http://weibo.com/parheliamm'),
    'vince' => array('name' => 'IsaacChen',
                     'url' => 'http://weibo.com/tingyiisaac'),
    'virgo' => array('name' => '乖奕虎',
                     'url' => 'http://weibo.com/guaiyihu'),
    'x3' => array('name' => 'zhaochengw',
                     'url' => 'http://weibo.com/1649884475'),
    'z2' => array('name' => 'Flour_Mo',
                     'url' => 'http://weibo.com/2036597861'),
    'z2pro' => array('name' => 'S___Y__',
                     'url' => 'http://weibo.com/2434134362'),
    'zoom' => array('name' => 'Flour_Mo',
                     'url' => 'http://weibo.com/2036597861'),
);
